version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/mocha test/unit/**.js -w
    environment:
      NODE_ENV: TEST
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/usr/app